#!/bin/sh
set -e

main() {
  cpp $1 | grep -v "^#" > tmp.c

  # JIT
  if [ "$2" = "" ]; then
    _ir tmp.c tmp.ll
    set +e
    lli tmp.ll
    local status=$?
    set -e
    rm tmp.ll
    exit $status
  fi

  case "${2##*.}" in
    "ll" )
      _ir tmp.c $2
      break;;
    "bc" )
      _ir tmp.c tmp.ll
      _bc tmp.ll $2
      break;;
    "s" | "asm" )
      _ir tmp.c tmp.ll
      _asm tmp.ll $2
      break;;
    "o" | "obj" )
      _ir tmp.c tmp.ll
      _asm tmp.ll tmp.s
      _obj tmp.s $2
      break;;
    * )
      echo "Unknown extention."
      exit 1
      break;;
    esac
}

_ir() {
  ./teal < $1 > $2
  rm $1
}

_bc() {
  llvm-as $1 -o $2
  rm $1
}

_asm() {
  llc $1 -o $2
  rm $1
}

_obj() {
  as $1 -o $2
  rm $1
}

main "$@"
