#!/bin/sh
set -e

main() {
  local status=0
  cpp $2 | grep -v "^#" > tmp.c
  case "$1" in
    "ir" | "ll" )
      _ir tmp.c $3
      break;;
    "bc" )
      _ir tmp.c tmp.ll
      _bc tmp.ll $3
      break;;
    "asm" )
      _ir tmp.c tmp.ll
      _asm tmp.ll $3
      break;;
    "obj" )
      _ir tmp.c tmp.ll
      _asm tmp.ll tmp.s
      _obj tmp.s $3
      break;;
    "jit" )
      _ir tmp.c tmp.ll
      set +e
      lli tmp.ll
      status=$?
      set -e
      rm tmp.ll
      break;;
    esac

    exit $status
}

_ir() {
  ./teal < $1 > $2
  rm $1
}

_bc() {
  llvm-as $1 -o $2
  rm $1
}

_asm() {
  llc $1 -o $2
  rm $1
}

_obj() {
  as $1 -o $2
  rm $1
}

main "$@"
