#!/bin/sh
set -e

main() {
  # JIT
  if [ "$2" = "" ]; then
    cpp $1 | grep -v "^#" > tmp.c
    _ir tmp.ll tmp.c
    set +e
    lli tmp.ll
    local status=$?
    set -e
    rm tmp.ll
    exit $status
  fi

  cpp $2 | grep -v "^#" > tmp.c

  case "${1##*.}" in
    "ll" )
      _ir $1 tmp.c
      break;;
    "bc" )
      _ir tmp.ll tmp.c
      _bc $1 tmp.ll
      break;;
    "s" | "asm" )
      _ir tmp.ll tmp.c
      _asm $1 tmp.ll
      break;;
    "o" | "obj" )
      _ir tmp.ll tmp.c
      _asm tmp.s tmp.ll
      _obj $1 tmp.s
      break;;
    * )
      echo "Unknown extention."
      exit 1
      break;;
    esac
}

_ir() {
  ./orig < $2 > $1
  rm $2
}

_bc() {
  llvm-as -o $1 $2
  rm $2
}

_asm() {
  llc -o $1 $2
  rm $2
}

_obj() {
  as -o $1 $2
  rm $2
}

main "$@"
